services:
  - type: web
    name: ai-knowledge-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn your_django_project.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: False
    plan: free

  - type: web
    name: ai-knowledge-frontend
    env: static
    buildCommand: yarn install && yarn build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://ai-knowledge-backend.onrender.com
